import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#424654',
        'on-secondary-fixed': '#000f5c',
        'surface-variant': '#e0e3e5',
        'surface-container-low': '#f2f4f6',
        'on-error-container': '#93000a',
        'inverse-primary': '#b2c5ff',
        'on-tertiary-fixed': '#380d00',
        'secondary': '#2d4add',
        'primary-fixed': '#dae2ff',
        'tertiary-fixed': '#ffdbcf',
        'primary-fixed-dim': '#b2c5ff',
        'on-secondary-fixed-variant': '#052fc8',
        'surface': '#f7f9fb',
        'secondary-fixed': '#dee0ff',
        'surface-bright': '#f7f9fb',
        'tertiary-container': '#a93802',
        'on-surface': '#191c1e',
        'surface-container-highest': '#e0e3e5',
        'primary-container': '#0056d2',
        'surface-container-high': '#e6e8ea',
        'on-primary-container': '#ccd8ff',
        'surface-tint': '#0056d2',
        'on-primary': '#ffffff',
        'outline-variant': '#c3c6d6',
        'on-secondary-container': '#fffbff',
        'on-error': '#ffffff',
        'surface-dim': '#d8dadc',
        'on-primary-fixed': '#001847',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#4b65f7',
        'surface-container': '#eceef0',
        'on-background': '#191c1e',
        'on-primary-fixed-variant': '#0040a1',
        'error-container': '#ffdad6',
        'tertiary': '#822800',
        'outline': '#737785',
        'on-tertiary-container': '#ffcebd',
        'on-tertiary-fixed-variant': '#812800',
        'secondary-fixed-dim': '#bac3ff',
        'on-secondary': '#ffffff',
        'error': '#ba1a1a',
        'primary': '#0040a1',
        'background': '#f7f9fb',
        'on-tertiary': '#ffffff',
        'tertiary-fixed-dim': '#ffb59b',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Lexend', 'sans-serif'],
        label: ['Lexend', 'sans-serif'],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        '3xl': '2.5rem',
        full: '9999px',
      },
      spacing: {
        6: '1.5rem',
        8: '2rem',
        10: '2.75rem',
        12: '3rem',
        14: '3.5rem',
      },
      backdropBlur: {
        xl: '24px',
      },
    },
  },
  plugins: [],
};

export default config;

